name: Check new patch
permissions: write-all
on:
  push:
    paths:
      - .github/workflows/ci.yml
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Check new patch ReX forked by anddea beta
        id: check-rex-anddea-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches prerelease rex-anddea.apk
      - name: Check new patch ReX Music forked by anddea beta
        id: check-rex-music-anddea-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches prerelease rex-music-anddea.apk
      - name: Check new patch Twitter Piko Beta
        id: check-twitter-piko-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko prerelease twitter-piko.apk
      - name: Check new patch Discord Pyoncord
        id: check-discord-pyoncord
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh pyoncord/bunnyxposed prerelease discord-pyoncord.apk
      - name: Keep workflow run
        if: steps.check-gh.outputs.internet_error == '0'
        uses: gautamkrishnar/keepalive-workflow@v1
      - name: Re-run workflow if github connection not stable
        if: always() && steps.check-rv.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: actions/github-script@v7
        with:
          script: |
            const maxRetries = ${{ env.max_retries }};
            let retryCount = ${{ env.retry_count }};
            if (retryCount < maxRetries) {
              retryCount += 1;
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "ci.yml",
                ref: context.ref,
                inputs: {
                  'retry_count': String(retryCount)
                }
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          retry_count: ${{ github.event.inputs.retry_count }}
          max_retries: 3
      - name: Summary
        if: steps.check-gh.outputs.internet_error == '0'
        run: |
          echo "ReX Anddea: ${{ steps.check-rex-anddea-beta.outputs.new_patch }}"
          echo "ReX Anddea Music: ${{ steps.check-rex-music-anddea-beta.outputs.new_patch }}"
          echo "Twitter Piko: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}"
          echo "Discord Pyoncord: ${{ steps.check-discord-pyoncord.outputs.new_patch }}"
    outputs:
      check_rex_anddea_beta: ${{ steps.check-rex-anddea-beta.outputs.new_patch }}
      check_rex_music_anddea_beta: ${{  steps.check-rex-music-anddea-beta.outputs.new_patch }}
      check_twitter_piko_beta: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}
      check_discord_pyoncord: ${{ steps.check-discord-pyoncord.outputs.new_patch }}

  Patch-ReX-anddea-beta:
    name: Patch ReX forked by anddea beta
    needs: check
    if: ${{ needs.check.outputs.check_rex_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Rex-anddea-beta-yt"
  Patch-ReX-Music-anddea-beta:
    name: Patch ReX Music forked by anddea beta
    needs: check
    if: ${{ needs.check.outputs.check_rex_music_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Rex-anddea-beta-music"
  Patch-Twitter-Piko-Beta:
    name: Patch Twitter Piko Beta
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Beta"
  Patch-Discord-Pyoncord:
    name: Patch Discord Pyoncord
    needs: check
    if: ${{ needs.check.outputs.check_discord_pyoncord == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Discord Pyoncord"
